kind: Template
apiVersion: v1
parameters:
- name: SERVICE_NAME
  required: true
  value: auth
- name: ENVIRONMENT
  value: dev
metadata:
  name: ${SERVICE_NAME}
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${SERVICE_NAME}
    labels:
      belongsTo: ${SERVICE_NAME}
      env: ${ENVIRONMENT}
  type: Opaque
  data:
    db.host: ZGItYXV0aA==
    db.port: NTQzMg==
    developer.mode.enabled: dHJ1ZQ==
    db.admin.password: bXlzZWNyZXRwYXNzd29yZA==