kind: Template
apiVersion: v1
parameters:
- name: SERVICE_NAME
  required: true
  value: auth
- name: ENVIRONMENT
  value: dev
metadata:
  name: ${SERVICE_NAME}
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${SERVICE_NAME}
    labels:
      belongsTo: ${SERVICE_NAME}
      env: ${ENVIRONMENT}
  type: Opaque
  data:
    db.host: ZGItYXV0aA==
    db.port: NTQzMg==
    developer.mode.enabled: dHJ1ZQ==
    db.admin.password: bXlzZWNyZXRwYXNzd29yZA==
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ${SERVICE_NAME}
    labels:
      belongsTo: ${SERVICE_NAME}
      env: ${ENVIRONMENT}
  type: Opaque
  data:
    wit.url: http://wit
    notification.serviceurl: http://f8notification
 #  you can set "ui.url" to your locally deployed ui. by default it's localhost:8080
 #  ui.url: http://ui
