# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

required = [
  "github.com/golang/lint/golint",
  "github.com/fzipp/gocyclo",
  "github.com/goadesign/goa/cors",
  "github.com/goadesign/goa/encoding/form",
  "github.com/goadesign/goa/goagen",
  "github.com/goadesign/goa/goagen/codegen",
  "github.com/goadesign/goa/goagen/gen_app",
  "github.com/goadesign/goa/goagen/gen_controller",
  "github.com/goadesign/goa/goagen/gen_swagger",
  "github.com/goadesign/goa/goagen/gen_client",
  "github.com/goadesign/goa/goagen/gen_js",
  "github.com/goadesign/goa/goagen/utils",
  "github.com/goadesign/goa/goatest",
  "github.com/fabric8-services/fabric8-wit/design",
  "github.com/fabric8-services/fabric8-notification/design",
  "github.com/fabric8-services/fabric8-tenant/design",
  "github.com/fabric8-services/fabric8-cluster/design",
  "github.com/jteeuwen/go-bindata/go-bindata",
  "github.com/jstemmer/go-junit-report",
  "github.com/wadey/gocovmerge",
  "github.com/pilu/fresh",
  "github.com/gojuno/minimock/cmd/minimock"
]

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.0.0"

[[constraint]]
  name = "github.com/goadesign/goa"
  version = "1.3.0"
  
[[constraint]]
  name = "github.com/lib/pq"
  version = "1.0.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "gopkg.in/square/go-jose.v2"
  version = "2.1.2"

[[constraint]]
  name = "github.com/jteeuwen/go-bindata"
  revision = "v3.0.7"

[[constraint]]
  name = "github.com/fabric8-services/fabric8-wit"
  revision = "f7b1641d891c194976363c4a74d1fe0b575491af"

[[constraint]]
  name = "github.com/fabric8-services/fabric8-notification"
  revision = "907d3253a9e8ae42f61ce7c931fd920df20ee0ec"

[[constraint]]
  name = "github.com/fabric8-services/fabric8-tenant"
  revision = "7e149ee841ea9fe7d439f206781b51cacde5d4d3"

[[constraint]]
  branch = "master"
  name = "github.com/fabric8-services/fabric8-cluster-client"

[[constraint]]
  name = "github.com/fabric8-services/fabric8-common"
  revision = "083c9c890cdf825027a0f009135af153d07d2926"

[[constraint]]
  name = "github.com/jstemmer/go-junit-report"
  revision = "1ce4b93a20c6a280a7d5c1ef38c44d0d8c6d80ea"

[[constraint]]
  name = "github.com/pilu/fresh"
  revision = "9c0092493eff2825c3abf64e087b3383dec939c3"

[[constraint]]
  name = "github.com/getsentry/raven-go"
  revision = "563b81fc02b75d664e54da31f787c2cc2186780b"

[[constraint]]
  name = "github.com/gojuno/minimock"
  revision = "a5502dd2746ee6fc3fd58ad83d701d25e14d68d1"

[[constraint]]
  name = "github.com/panjf2000/ants"
  version = "v4.1"

[[constraint]]
  name = "cirello.io/pglock"
  source = "github.com/alexeykazakov/pglock"
  revision = "0759a5f88d75b7629df0a9714e7fa34f6efb4d07"

[prune]
  go-tests = true
  unused-packages = true 
