kind: Template
apiVersion: v1
metadata:
  name: auth
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: auth
  type: Opaque
  data:
    db.host: ZGI=
    db.port: NTQzMg==
    db.user: cG9zdGdyZXM=
    db.password: bXlzZWNyZXRwYXNzd29yZA==
    keycloak.realm: ZmFicmljOAo=
    keycloak.secret: Cg==
    serviceaccount.privatekey: Cg==
    serviceaccount.privatekeyid: Cg==
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: auth
  type: Opaque
  data:
    postgres.sslmode: require
    postgres.connection.maxidle: "90"
    postgres.connection.maxopen: "90"
    redirect.valid: ".*"
    notapproved_redirect: ""
    keycloak.url: "https://sso.openshift.io"
  