kind: Template
apiVersion: v1
metadata:
  name: auth
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: auth
  type: Opaque
  data:
    db.host: ZGI=
    db.port: NTQzMg==
    db.user: cG9zdGdyZXM=
    db.password: bXlzZWNyZXRwYXNzd29yZA==
    auth.provider.client.id: Cg==
    auth.provider.client.secret: Cg==
    auth.provider.endpoint.auth: Cg==
    auth.provider.endpoint.userinfo: Cg==
    auth.provider.endpoint.token: Cg==
    auth.provider.endpoint.logout: Cg==
    serviceaccount.privatekey: Cg==
    serviceaccount.privatekeyid: Cg==
    useraccount.privatekey: Cg==
    useraccount.privatekeyid: Cg==
    github.client.id: Cg==
    github.client.secret: Cg==
    sentry.dsn: c2VjcmV0
    oso.client.apiurl: aHR0cHM6Ly9hcGkuY29uc29sZS5zdGFydGVyLXVzLWVhc3QtMi5vcGVuc2hpZnQuY29t
    tenantsvc.url: aHR0cDovL2Y4dGVuYW50Ojgw
    oso.regapp.admin.username: Cg==
    oso.regapp.admin.token: Cg==
    oso.regapp.url: Cg==
- apiVersion: v1
  kind: Secret
  metadata:
    name: auth-config-files
  type: Opaque
  data:
    service.account.secrets: >-
      ew0KICAgICJhY2NvdW50cyI6IFsNCiAgICAgICAgew0KICAgICAgICAgICAgIm5hbWUiOiJmYWJyaWM4LXdpdCIsDQogICAgICAgICAgICAiaWQiOiI1ZGVjNWZkYi0wOWUzLTQ0NTMtYjczZi01YzgyODgzMmIyOGUiLA0KICAgICAgICAgICAgInNlY3JldHMiOlsiJDJhJDA0JG5JN3o3UmU0cGJ4LlY1dndtMTRuNS52ZWxoQi5uYk1neGRaMHZTb21XVnhjY3QzNHpiSDllIl0NCiAgICAgICAgfSwNCiAgICAgICAgew0KICAgICAgICAgICAgIm5hbWUiOiJmYWJyaWM4LXRlbmFudCIsDQogICAgICAgICAgICAiaWQiOiJjMjExZjFiZC0xN2E3LTRmOGMtOWY4MC0wOTE3ZDE2Nzg4OWQiLA0KICAgICAgICAgICAgInNlY3JldHMiOlsiJDJhJDA0JHlucU0vc3lLTVlvd01JbjVjeXFIdWV2V25meklRcXR5WTRtLjYxQjAycWx0WTVTT3lHSU9lIiwgIiQyYSQwNCRzYkMvQWZXMmMzM2h2OG9yR0EuMUQuTFhhLy5JWTc2Vldoc2ZxeENWaHJoRmtEZkwwL1hHSyJdDQogICAgICAgIH0sDQogICAgICAgIHsNCiAgICAgICAgICAgICJuYW1lIjoiZmFicmljOC1qZW5raW5zLWlkbGVyIiwNCiAgICAgICAgICAgICJpZCI6IjM0MWMyODNmLTBjZDctNDhhOC05MjgxLTQ1ODNhY2ViMzYxNyIsDQogICAgICAgICAgICAic2VjcmV0cyI6WyIkMmEkMTAkR0xQSDguZDNWNHZKLk05bDdCTG13LkV4VHlISlIuNko0VzFCMnJ0dFFOcjh4ZnpaQy5lTy4iXQ0KICAgICAgICB9LA0KICAgICAgICB7DQogICAgICAgICAgICAibmFtZSI6ImZhYnJpYzgtb3NvLXByb3h5IiwNCiAgICAgICAgICAgICJpZCI6Ijk2ZWUzZjkxLWY5ODAtNDI5Zi1hNGU4LTA2MGMzMjU4MDMxZCIsDQogICAgICAgICAgICAic2VjcmV0cyI6WyIkMmEkMTAkR0xQSDguZDNWNHZKLk05bDdCTG13LkV4VHlISlIuNko0VzFCMnJ0dFFOcjh4ZnpaQy5lTy4iXQ0KICAgICAgICB9LA0KICAgICAgICB7DQogICAgICAgICAgICAibmFtZSI6Im9ubGluZS1yZWdpc3RyYXRpb24iLA0KICAgICAgICAgICAgImlkIjoiZjg2N2VjNzItMzE3MS00YjhmLThlZWMtOTBhMzJlYWI2ZTBiIiwNCiAgICAgICAgICAgICJzZWNyZXRzIjpbIiQyYSQxMCRHTFBIOC5kM1Y0dkouTTlsN0JMbXcuRXhUeUhKUi42SjRXMUIycnR0UU5yOHhmelpDLmVPLiJdDQogICAgICAgIH0sDQogICAgICAgIHsNCiAgICAgICAgICAgICJuYW1lIjoiZmFicmljOC1ub3RpZmljYXRpb24iLA0KICAgICAgICAgICAgImlkIjoiNGMzNGY2ZDQtZjAwYi00ODdiLTlhMWYtZTdkMWFkYmE2ODY2IiwNCiAgICAgICAgICAgICJzZWNyZXRzIjpbIiQyYSQxMCRHTFBIOC5kM1Y0dkouTTlsN0JMbXcuRXhUeUhKUi42SjRXMUIycnR0UU5yOHhmelpDLmVPLiJdDQogICAgICAgIH0sDQogICAgICAgIHsNCiAgICAgICAgICAgICJuYW1lIjoicmgtY2hlIiwNCiAgICAgICAgICAgICJpZCI6ImQ2ZDViNTY4LThhM2MtNGU0Mi1iY2FjLWFkZWIxNGViM2IxNSIsDQogICAgICAgICAgICAic2VjcmV0cyI6WyIkMmEkMTAkR0xQSDguZDNWNHZKLk05bDdCTG13LkV4VHlISlIuNko0VzFCMnJ0dFFOcjh4ZnpaQy5lTy4iXQ0KICAgICAgICB9DQogICAgXQ0KfQ==
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: auth
  type: Opaque
  data:
    postgres.sslmode: require
    postgres.connection.maxidle: "90"
    postgres.connection.maxopen: "90"
    redirect.valid: ".*"
    notapproved_redirect: ""
    keycloak.url: https://sso.openshift.io
    notification.serviceurl: ""
    email.verify.url: https://prod-preview.openshift.io/_home
    invitation.accepted.url: https://prod-preview.openshift.io/_home
    environment: prod-preview
    ignore.email.prod: ".+\\+preview.*\\@redhat\\.com"
    user.deactivation.notification.enabled: false
    user.deactivation.enabled: false
  